### PR TITLE
Fixes for latest pkg:asn1lib (now fewer nulls)

### PR DESCRIPTION
**Pull request by kevmoo**
Requires Dart 3.0
Some tiny lint cleanups
Prepare to release v0.2.4

### CODE REVIEW

**Comment by kevmoo** [comment]
@rbellens ?

**Comment by PROGrand** [comment]
@rbellens
+1

**Comment by gmpassos** [comment]
FYI: @appsup-dart @rbellens @jeroentrappers @nakajo2011

**Comment by ahmednfwela** [comment]
published a new package that includes this PR until the maintainers are back
https://pub.dev/packages/x509_plus/

**Comment by rbellens** [comment]
are there any changes in this pr that are not covered by #25?

**Comment by kevmoo** [comment]
That should be good! thank you!

**Pull request closed without merging**
