### PR TITLE
Remove null check

### LINKED ISSUE #28: `x509 0.2.4` still warning about null-aware operation.
```text
~/.pub-cache/hosted/pub.dev/x509-0.2.4/lib/src/extension.dart:45:48: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
      ASN1Parser(sequence.elements[octetIndex].contentBytes()!).nextObject(),
```

```
x509 0.2.4
asn1lib: ^1.5.0
```

`Dart SDK version: 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "macos_x64"`

### PR DESCRIPTION
**Pull request by wstrange**
Fixes #28

### CODE REVIEW

**Comment by lazy-demon** [comment]
pls merge!

**Comment by wstrange** [comment]
@rbellens any updates?

**Comment by slightfoot** [comment]
@rbellens would it be possible to get this merged?

**Comment by wstrange** [comment]
@rbellens  This is a trivial one liner merge.  Can you please merge / publish.

Thanks

**Comment by rbellens** [comment]
sorry for waiting. This is now merged.

**Pull request closed without merging**
